config/routes.rb
Rails.application.routes.draw do
  resources :uploads
  resources :locations
  resources :bookings
  
  get 'listings' => "rooms#listings"
  get 'inactive-listings' => "rooms#inactive_listings"
  
  get 'reservations' => 'bookings#reservations'
  get 'checked-in' => 'bookings#checked_in'
  get 'checked-out' => 'bookings#checked_out'
  get 'guest-cancelled' => 'bookings#guest_cancelled'
  get 'no-shows' => 'bookings#no_shows'

  get 'pending-transfers' => 'bookings#transfer_pending'
  get 'confirmed-transfers' => 'bookings#transfer_confirm'

  get 'upcoming' => "bookings#upcoming"
  get 'departed' => "bookings#departed"
  get 'cancelled' => "bookings#cancelled"
  
  match 'update_listing_status' => "rooms#update_listing_status", via: :post

  match 'update_status' => "bookings#update_status", via: :post
  match 'cancel_booking' => "bookings#cancel_booking", via: :post
  match 'checking_out' => "bookings#checking_out", via: :post
  match 'verify_transfer' => "bookings#verify_transfer", via: :post

  get 'rooms/update_timeslots', :as => 'update_timeslots'
  get 'rooms/block_timeslots', :as => 'block_timeslots'
  get 'rooms/block_timeslots_next', :as => 'block_timeslots_next'


  get 'payment-instruction' => "bookings#payment_instruction"
 
  resources :rooms do
    resources :room_steps, path: "steps", only: [:show, :update]
  	collection do
  		match 'search' => 'rooms#search', via: [:get, :post], as: :search
      match 'search-refined' => 'rooms#search_refined', via: [:get, :post], as: :search_refined
  		match 'book' => 'rooms#book', via: [:get, :post], as: :book
  	end
  end

  get 'rooms/:id/calendar' => "rooms#calendar", as: :calendar
  
  resources :areas
  
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]

  root 'welcome#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  monetize :subtotal_sens, :service_fee_sens, :total_sens

  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"

  #validates :first_name, :last_name, :email, :phone, presence: true

  scope :that_are_paid, -> { where paid: true }


  include DateTimeAttribute
  date_time_attribute :check_in, :check_out
  #scope :on, lambda {|day = Date.today| where('start > ? AND end < ?', day, day)}

  def start_time
    self.check_in ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
  end

  def paypal_url(return_path)
    values = {
              business: "phidiaslo@gmail.com",
              cmd: "_cart",
              upload: 1,
              return: "#{Rails.application.secrets.app_host}#{return_path}",
              invoice: id,
              currency_code: 'MYR',
              item_name_1: room.title,
              amount_1: room.service_fee,
              notify_url: "#{Rails.application.secrets.app_host}/payment_notifications"
            }
    "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end

  def self.generate_booking_code(size = 4)
    charset = %w{ 2 3 4 6 7 9 A C D E F G H J K M N P Q R T V W X Y Z}
    (0...size).map{ charset.to_a[rand(charset.size)] }.join
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy, :verify_transfer, :cancel_booking, :update_status, :checking_out]
  before_filter :admin_signed_in?, only: [:index, :transfer_pending, :transfer_confirm, :verify_transfer, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def payment_instruction
  end

  def transfer_pending
    @bookings = Booking.where(paid: false, payment_method: "Bank Transfer").includes(:buyer)
  end

  def transfer_confirm
    @bookings = Booking.where(paid: true, payment_method: "Bank Transfer").includes(:buyer)
  end

  def verify_transfer
    if params[:commit] == "Confirm"
      @booking.update_attributes(paid: true)
      #send_message(@booking.phone, "Thanks for the payment! Your HourBeds booking #{@booking.id} is confirmed. Visit HourBeds.com for more info")
      #send message to seller
    elsif params[:commit] == "Delete"
      @booking.destroy
    end
    redirect_to pending_transfers_url
  end

  def reservations
    @bookings = Booking.where(seller_id: current_user.id, status: "Upcoming").that_are_paid
  end

  def checked_in
    @bookings = Booking.where(seller_id: current_user.id, status: "Checked In")
  end

  def checked_out
    @bookings = Booking.where(seller_id: current_user.id, status: "Checked Out")
  end

  def no_shows
    @bookings = Booking.where(seller_id: current_user.id, status: "No Show")
  end

  def guest_cancelled
    @bookings = Booking.where(seller_id: current_user.id, status: "Cancelled")
  end

  def upcoming
    @bookings = Booking.where("buyer_id = ? AND start_date >= ? AND status != ? AND status != ?  AND payment_method != ?", current_user.id, Date.today, "Cancelled", "No Show", "Block")
  end

  def departed
    @bookings = Booking.where("buyer_id = ? AND start_date < ? AND status != ? AND status != ? AND payment_method != ?", current_user.id, Date.today, "Cancelled", "No Show", "Block")
  end

  def cancelled
    @bookings = Booking.where(buyer_id: current_user.id, status: "Cancelled")
  end

  def cancel_booking
    @booking.update_attribute(:status, "Cancelled")
    redirect_to upcoming_url
  end

  def update_status
    if params[:commit] == "Check In"
      @booking.update_attribute(:status, "Checked In")
    elsif params[:commit] == "No Show"
      @booking.update_attribute(:status, "No Show")
    end
    redirect_to reservations_url
  end

  def checking_out
    @booking.update_attribute(:status, "Checked Out")
    redirect_to reservations_url
  end

  def index
    @bookings = Booking.all.order('id ASC').that_are_paid
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    room = Room.find(@booking.room_id)    
    
    @booking.buyer_id = current_user.id if user_signed_in?
    @booking.seller_id = room.user_id
    @booking.room_name = room.name
    @booking.room_title = room.title
    @booking.booking_code = Booking.generate_booking_code
    if params[:payment_method].present?
      @booking.payment_method = params[:payment_method]
    else
      @booking.payment_method = "Block"
    end

    respond_to do |format|
      if @booking.save
        if @booking.payment_method == "Bank Transfer"
          #send_message("+15005550006", "[HB][##{@booking.id}] Brace yourself for RM#{@booking.service_fee} bank transfer from #{@booking.first_name}(#{@booking.phone}). Visit HourBeds.com for more info")
          format.html { redirect_to payment_instruction_url(transfer: @booking.total) }
        elsif @booking.payment_method == "Block"
          format.html { redirect_to calendar_url(room, start_date: @booking.start_date) }
        else
          #format.html { redirect_to booking_url(@booking), notice: 'Booking was successfully created.' }
          #send_message("+15005550006", "You got a #{@booking.duration} hour reservation for #{@booking.room_name.truncate(20)} (#{@booking.check_in.strftime("%b %d, %Y - %l:%M %p")}). Visit HourBeds.com for more info")
        end
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to bookings_url, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      if @booking.payment_method == 'Block'
        format.html { redirect_to calendar_url(@booking.room_id) }
        format.json { head :no_content }
      else
        format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    def send_message(number, message)
      twilio_number = ENV["twilio_number"]
      client = Twilio::REST::Client.new(ENV["twilio_account_sid"], ENV["twilio_auth_token"])
      phone_number = number #"+15005550001"

      message = client.account.messages.create(
        :from => twilio_number,
        :to => phone_number,
        :body => message,
      )
      puts message.to
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:seller_id, :buyer_id, :room_id, :first_name, :last_name,
                                      :email, :phone, :duration, :guest, :subtotal, 
                                      :service_fee, :total, :room_name, :room_title, :status, :paid,
                                      :check_in, :check_out, :start_date, :booking_code, :payment_method)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :seller_id %>
    <%= f.input :buyer_id %>
    <%= f.input :room_id %>
    <%= f.input :duration %>
    <%= f.input :subtotal %>
    <%= f.input :service_fee %>
    <%= f.input :total %>
    <%= f.input :room_name %>
    <%= f.input :start_date %>
    <%= f.input :check_in %>
    <%= f.input :check_out %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/checked_in.html.erb
<% title 'Your Guests - Checked In' %>
<% noindex %>
<%= render 'layouts/header' %>

<div class="subnav desktop-visible">
  <ul class="subnav-list">
    <div class="container">
      <li><%= link_to "Your Guests", reservations_path, class: "subnav-item zeroLeft active" %></li>
      <li><%= link_to "Your Listings", listings_path, class: "subnav-item" %></li>
      <li><%= link_to "Your Staycations", upcoming_path, class: "subnav-item" %></li>
      <li><%= link_to "Your Account", edit_user_path(current_user), class: "subnav-item" %></li>
    </div>
  </ul>
</div>
<div id="mobile-subnav" class="mobile-visible">
  <ul class="nav navbar-nav">
    <li>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        Your Guests <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Pending Arrival", reservations_path %></li>
        <li><%= link_to "Checked In", checked_in_path %></li>
        <li><%= link_to "Checked Out", checked_out_path %></li>
        <li><%= link_to "Cancelled", guest_cancelled_path %></li>
        <li><%= link_to "No Shows", no_shows_path %></li>
      </ul>
    </li>
  </ul>
</div>
<div class="container">
<div class="row">
  <div class="col-md-2 desktop-visible">
    <ul class="sidebar-list">
      <li><%= link_to "Pending Arrival", reservations_path %></li>
      <li><%= link_to "Checked In", checked_in_path, class: "active" %></li>
      <li><%= link_to "Checked Out", checked_out_path %></li>
      <li><%= link_to "Cancelled", guest_cancelled_path %></li>
      <li><%= link_to "No Shows", no_shows_path %></li>
    </ul>
  </div>
  <div class="col-md-10">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Checked In</h3>
    </div>
    <div id="table-wrapper" class="panel-body">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Checked In</th>
            <th>Room</th>
            <th>Customer</th>
            <th>Price</th>
            <th>Action Required</th>
          </tr>
        </thead>
        <tbody>
          <% @bookings.each do |booking| %>
            <tr>
              <td><%= booking.id %></td>
              <td>
                <%= "#{booking.check_in.strftime("%b %d, %Y - %l:%M %p")}" %>
                <p><small><%= "#{booking.guest} guest for #{booking.duration} hour" %></small></p>
              </td>
              <td><%= link_to booking.room_name, room_path(id: booking.room_id, start_date: Date.today, duration: 3) %></td>
              <td>
                <%= "#{booking.first_name} #{booking.last_name}" %>
              </td>
              <td>
                <b><%= booking.subtotal.format(symbol_before_without_space: false) %></b>
                <p><small>DEP: RM 100.00</small></p>
              </td>
              <td>
                <%= form_tag checking_out_path(id: booking) do %>
                  <%= submit_tag "Check Out", data: { confirm: 'Your confirm message' }, class: "btn btn-primary full-width" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
  </div>
    
  </div>
</div>
</div>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<% title 'Admin - Bookings' %>
<% noindex %>
<%= render 'layouts/header' %>

<div class="subnav desktop-visible">
  <ul class="subnav-list">
    <div class="container">
      <li><%= link_to "Bank Transfers", pending_transfers_path, class: "subnav-item zeroLeft" %></li>
      <li><%= link_to "Bookings", bookings_path, class: "subnav-item active" %></li>
      <li><%= link_to "Listings", rooms_path, class: "subnav-item" %></li>
      <li><%= link_to "Images", uploads_path, class: "subnav-item" %></li>
      <li><%= link_to "Users", users_path, class: "subnav-item" %></li>
      <li><%= link_to "Areas", areas_path, class: "subnav-item" %></li>
      <li><%= link_to "Countries", locations_path, class: "subnav-item" %></li>
    </div>
  </ul>
</div>

<div id="mobile-subnav" class="mobile-visible">
  <ul class="nav navbar-nav">
    <li>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        Site Manager <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Bank Transfers", pending_transfers_path %></li>
        <li><%= link_to "Bookings", bookings_path %></li>
        <li><%= link_to "Listings", rooms_path %></li>
        <li><%= link_to "Images", uploads_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Areas", areas_path %></li>
        <li><%= link_to "Countries", locations_path %></li>
      </ul>
    </li>
  </ul>
</div>

<div class="container">
<div class="table-responsive">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Check In</th>
      <th>Room</th>
      <th>Customer</th>
      <th>Total</th>
      <th>Pay Seller</th>
      <th>Paid Us</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= link_to booking.id, booking %></td>
        <td>
          <%= "#{booking.check_in.strftime("%b %d, %Y - %l:%M %p")}" %>
          <p><small><%= "#{booking.guest} guest for #{booking.duration} hour" %></small></p>
          <%= "#{booking.check_out.strftime("%b %d, %Y - %l:%M %p")}" %>
          <span class="label label-info"><%= booking.status %></span>
        </td>
        <td>
          <%= link_to booking.room_title, room_path(id: booking.room_id, start_date: Date.today, duration: 3) %>
          <p><small><%= booking.room_name %></small></p>
          <p><%= "seller_id: #{booking.seller_id}" %></p>
        </td>
        <td>
          <%= booking.first_name %> <%= booking.last_name %>
          <p><small><b><%= booking.booking_code %></b></small></p>
          <p><%= "buyer_id: #{booking.buyer_id}" %></p>
        </td>
        <td><%= booking.total.format(symbol_before_without_space: false) %><p><small><%= booking.payment_method %></small></p></td>
        <td><%= booking.subtotal.format(symbol_before_without_space: false) %></td>
        <td>
          <b><%= booking.service_fee.format(symbol_before_without_space: false) %></b>
        </td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/no_shows.html.erb
<% title 'Your Guests - No Shows' %>
<% noindex %>
<%= render 'layouts/header' %>

<div class="subnav desktop-visible">
  <ul class="subnav-list">
    <div class="container">
      <li><%= link_to "Your Guests", reservations_path, class: "subnav-item zeroLeft active" %></li>
      <li><%= link_to "Your Listings", listings_path, class: "subnav-item" %></li>
      <li><%= link_to "Your Staycations", upcoming_path, class: "subnav-item" %></li>
      <li><%= link_to "Your Account", edit_user_path(current_user), class: "subnav-item" %></li>
    </div>
  </ul>
</div>

<div id="mobile-subnav" class="mobile-visible">
  <ul class="nav navbar-nav">
    <li>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        Your Guests <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Pending Arrival", reservations_path %></li>
        <li><%= link_to "Checked In", checked_in_path %></li>
        <li><%= link_to "Checked Out", checked_out_path %></li>
        <li><%= link_to "Cancelled", guest_cancelled_path %></li>
        <li><%= link_to "No Shows", no_shows_path %></li>
      </ul>
    </li>
  </ul>
</div>

<div class="container">
<div class="row">
  <div class="col-md-2 desktop-visible">
    <ul class="sidebar-list">
      <li><%= link_to "Pending Arrival", reservations_path %></li>
      <li><%= link_to "Checked In", checked_in_path %></li>
      <li><%= link_to "Checked Out", checked_out_path %></li>
      <li><%= link_to "Cancelled", guest_cancelled_path %></li>
      <li><%= link_to "No Shows", no_shows_path, class: "active" %></li>
    </ul>
  </div>
  <div class="col-md-10">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">No Shows</h3>
    </div>
    <div id="table-wrapper" class="panel-body">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Check In</th>
            <th>Room</th>
            <th>Customer</th>
            <th>Price</th>
            <th>Status</th>
          </tr>
        </thead>
        <tbody>
          <% @bookings.each do |booking| %>
            <tr>
              <td><%= booking.id %></td>
              <td>
                <%= "#{booking.check_in.strftime("%b %d, %Y - %l:%M %p")}" %>
                <p><small><%= "#{booking.guest} guest for #{booking.duration} hour" %></small></p>
              </td>
              <td><%= link_to booking.room_name, room_path(id: booking.room_id, start_date: Date.today, duration: 3) %></td>
              <td>
                <%= "#{booking.first_name} #{booking.last_name}" %>
                <p><small><b><%= booking.booking_code %></b></small></p>
              </td>
              <td>
                <b><%= booking.subtotal.format(symbol_before_without_space: false) %></b>
                <p><small>DEP: RM 100.00</small></p>
              </td>
              <td>
                <%= booking.status%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
  </div>
    
  </div>
</div>
</div>

app/views/bookings/reservations.html.erb
<% title 'Your Guests - Pending Arrival' %>
<% noindex %>
<%= render 'layouts/header' %>

<div class="subnav desktop-visible">
  <ul class="subnav-list">
    <div class="container">
      <li><%= link_to "Your Guests", reservations_path, class: "subnav-item zeroLeft active" %></li>
      <li><%= link_to "Your Listings", listings_path, class: "subnav-item" %></li>
      <li><%= link_to "Your Staycations", upcoming_path, class: "subnav-item" %></li>
      <li><%= link_to "Your Account", edit_user_path(current_user), class: "subnav-item" %></li>
    </div>
  </ul>
</div>
<div id="mobile-subnav" class="mobile-visible">
  <ul class="nav navbar-nav">
    <li>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        Your Guests <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Pending Arrival", reservations_path %></li>
        <li><%= link_to "Checked In", checked_in_path %></li>
        <li><%= link_to "Checked Out", checked_out_path %></li>
        <li><%= link_to "Cancelled", guest_cancelled_path %></li>
        <li><%= link_to "No Shows", no_shows_path %></li>
      </ul>
    </li>
  </ul>
</div>
<div class="container">
<div class="row">
  <div class="col-md-2 desktop-visible">
    <ul class="sidebar-list">
      <li><%= link_to "Pending Arrival", reservations_path, class: "active" %></li>
      <li><%= link_to "Checked In", checked_in_path %></li>
      <li><%= link_to "Checked Out", checked_out_path %></li>
      <li><%= link_to "Cancelled", guest_cancelled_path %></li>
      <li><%= link_to "No Shows", no_shows_path %></li>
    </ul>
  </div>
  <div class="col-md-10">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Pending Arrival</h3>
    </div>
    <div id="table-wrapper" class="panel-body">
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Check In</th>
            <th>Room</th>
            <th>Customer</th>
            <th>Price</th>
            <th>Status</th>
            <th>Action Required</th>
          </tr>
        </thead>
        <tbody>
          <% @bookings.each do |booking| %>
            <tr>
              <td><%= booking.id %></td>
              <td>
                <%= "#{booking.check_in.strftime("%b %d, %Y - %l:%M %p")}" %>
                <p><small><%= "#{booking.guest} guest for #{booking.duration} hour" %></small></p>
              </td>
              <td><%= link_to booking.room_name, room_path(id: booking.room_id, start_date: Date.today, duration: 3) %></td>
              <td>
                <%= "#{booking.first_name} #{booking.last_name}" %>
                <p><small><b><%= booking.booking_code %></b></small></p>
              </td>
              <td>
                <b><%= booking.subtotal.format(symbol_before_without_space: false) %></b>
                <p><small>DEP: RM 100.00</small></p>
              </td>
              <td><%= booking.status %></td>
              <td>
                <%= form_tag update_status_path(id: booking) do %>
                  <%= submit_tag "Check In", data: { confirm: 'Your confirm message' }, class: "btn btn-sm btn-success" %>
                  <%= submit_tag "No Show", data: { confirm: 'Your confirm message' }, class: "btn btn-sm btn-default" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
  </div>
    
  </div>
</div>
</div>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Seller:</strong>
  <%= @booking.seller_id %>
</p>

<p>
  <strong>Buyer:</strong>
  <%= @booking.buyer_id %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @booking.duration %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= @booking.subtotal %>
</p>

<p>
  <strong>Service fee:</strong>
  <%= @booking.service_fee %>
</p>

<p>
  <strong>Total:</strong>
  <%= @booking.total %>
</p>

<p>
  <strong>Name:</strong>
  <%= @booking.room_name %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/transfer_pending.html.erb
<% title 'Bank Transfers - Pending Transfers' %>
<% noindex %>
<%= render 'layouts/header' %>

<div class="subnav desktop-visible">
  <ul class="subnav-list">
    <div class="container">
      <li><%= link_to "Bank Transfers", pending_transfers_path, class: "subnav-item zeroLeft active" %></li>
      <li><%= link_to "Bookings", bookings_path, class: "subnav-item" %></li>
      <li><%= link_to "Listings", rooms_path, class: "subnav-item" %></li>
      <li><%= link_to "Images", uploads_path, class: "subnav-item" %></li>
      <li><%= link_to "Users", users_path, class: "subnav-item" %></li>
      <li><%= link_to "Areas", areas_path, class: "subnav-item" %></li>
      <li><%= link_to "Countries", locations_path, class: "subnav-item" %></li>
    </div>
  </ul>
</div>
<div id="mobile-subnav" class="mobile-visible">
  <ul class="nav navbar-nav">
    <li>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        Site Manager <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Bank Transfers", pending_transfers_path %></li>
        <li><%= link_to "Bookings", bookings_path %></li>
        <li><%= link_to "Listings", rooms_path %></li>
        <li><%= link_to "Images", uploads_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Areas", areas_path %></li>
        <li><%= link_to "Countries", locations_path %></li>
      </ul>
    </li>
  </ul>
</div>
<div class="container">
<div class="row">
  <div class="col-md-2">
    <ul class="sidebar-list">
      <li><%= link_to "Pending Transfers", pending_transfers_path, class: "active" %></li>
      <li><%= link_to "Confirmed Transfers", confirmed_transfers_path %></li>
    </ul>
  </div>
  <div class="col-md-10">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Pending Transfers</h3>
    </div>
    <div class="panel-body">
    <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Room</th>
          <th>Customer</th>
          <th>Contact</th>
          <th>Amount</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @bookings.each do |booking| %>
          <tr>
            <td><%= booking.id %></td>
            <td>
              <%= link_to booking.room_title, room_path(id: booking.room_id, start_date: Date.today, duration: 3) %>
            </td>
            <td>
              <%= booking.first_name %> <%= booking.last_name %>
            </td>
            <td>
              <%= booking.buyer.phone %>
              <p><small><%= mail_to booking.buyer.email %></small></p>
            <td>
              <b><%= booking.total.format(symbol_before_without_space: false) %></b>
            </td>
            <td>
              <%= form_tag verify_transfer_path(id: booking) do %>
                <%= submit_tag "Confirm", data: { confirm: 'Your confirm message' }, class: "btn btn-sm btn-success" %>
                <%= submit_tag "Delete", data: { confirm: 'Your confirm message' }, class: "btn btn-sm btn-danger" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    </div>
  </div>
    
  </div>
</div>
</div>
