config/routes.rb
Rails.application.routes.draw do
  resources :uploads
  resources :locations
  resources :bookings
  
  get 'listings' => "rooms#listings"
  get 'inactive-listings' => "rooms#inactive_listings"
  
  get 'reservations' => 'bookings#reservations'
  get 'checked-in' => 'bookings#checked_in'
  get 'checked-out' => 'bookings#checked_out'
  get 'guest-cancelled' => 'bookings#guest_cancelled'
  get 'no-shows' => 'bookings#no_shows'

  get 'pending-transfers' => 'bookings#transfer_pending'
  get 'confirmed-transfers' => 'bookings#transfer_confirm'

  get 'upcoming' => "bookings#upcoming"
  get 'departed' => "bookings#departed"
  get 'cancelled' => "bookings#cancelled"
  
  match 'update_listing_status' => "rooms#update_listing_status", via: :post

  match 'update_status' => "bookings#update_status", via: :post
  match 'cancel_booking' => "bookings#cancel_booking", via: :post
  match 'checking_out' => "bookings#checking_out", via: :post
  match 'verify_transfer' => "bookings#verify_transfer", via: :post

  get 'rooms/update_timeslots', :as => 'update_timeslots'
  get 'rooms/block_timeslots', :as => 'block_timeslots'
  get 'rooms/block_timeslots_next', :as => 'block_timeslots_next'


  get 'payment-instruction' => "bookings#payment_instruction"
 
  resources :rooms do
    resources :room_steps, path: "steps", only: [:show, :update]
  	collection do
  		match 'search' => 'rooms#search', via: [:get, :post], as: :search
      match 'search-refined' => 'rooms#search_refined', via: [:get, :post], as: :search_refined
  		match 'book' => 'rooms#book', via: [:get, :post], as: :book
  	end
  end

  get 'rooms/:id/calendar' => "rooms#calendar", as: :calendar
  
  resources :areas
  
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]

  root 'welcome#index'

end

app/models/area.rb
class Area < ActiveRecord::Base
  belongs_to :location
  has_many :rooms

  DURATION_SELECT = [["3 hours", "3"], ["4 hours", "4"], ["5 hours", "5"], ["6 hours", "6"], ["7 hours", "7"], ["8 hours", "8"], ["9 hours", "9"]]

  def self.get_name(id)
    find_by_id(id).name
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]
  before_filter :admin_signed_in?, only: [:index]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all.includes(:location)
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
    @areas = Area.all
    @search = Room.ransack(params[:q])

    if @search.present?
      @rooms = @search.result(distinct: true)
    else
      @rooms = Room.where(area_id: @area)
    end
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:name, :location_id)
    end
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/_form.html.erb
<%= simple_form_for(@area) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-inputs">
    <%= f.input :location_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/areas/backup_search.html.erb
      <%= form_tag search_rooms_path, method: :post do %>
        <div class="row">
          <div class="col-md-6 padRight-5">
            <%= select_tag :area, options_for_select(@areas.collect {|u| [ u.name, u.id ] }), prompt: "Select destination", class: "form-input select-fix marBot-10 noBor" %>
          </div>
          <div class="col-md-6 padLeft-5">
            <%= select_tag :duration, options_for_select(Area::DURATION_SELECT), prompt: "Select duration", class: "form-input select-fix marBot-10 noBor" %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6 padRight-5">
            <%= text_field_tag :date, params[:date], placeholder: 'Select date', autocomplete: 'off', readonly: true, class: "form-input marBot-15 noBor datepicker1" %>
          </div>
          <div class="col-md-6 padLeft-5">
            <%= select_tag :time, options_for_select(Area::TIME_SELECT), prompt: "Select time", class: "form-input select-fix marBot-15 noBor" %>
          </div>
        </div>  
          
          <%= button_tag "Find Rooms", data: {disable_with: "WAIT..."}, class: "btn btn-lg btn-danger full-width" %>
      <% end %>


                  <%= f.select(:duration_eq, Area::DURATION_SELECT, {prompt: "Select duration"}, {class: "form-input select-fix marBot-10 noBor"}) %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form' %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<% title 'Admin - Cities' %>
<% noindex %>
<%= render 'layouts/header' %>

<div class="subnav desktop-visible">
  <ul class="subnav-list">
    <div class="container">
      <li><%= link_to "Bank Transfers", pending_transfers_path, class: "subnav-item zeroLeft" %></li>
      <li><%= link_to "Bookings", bookings_path, class: "subnav-item" %></li>
      <li><%= link_to "Listings", rooms_path, class: "subnav-item" %></li>
      <li><%= link_to "Images", uploads_path, class: "subnav-item" %></li>
      <li><%= link_to "Users", users_path, class: "subnav-item" %></li>
      <li><%= link_to "Areas", areas_path, class: "subnav-item active" %></li>
      <li><%= link_to "Countries", locations_path, class: "subnav-item" %></li>
    </div>
  </ul>
</div>

<div id="mobile-subnav" class="mobile-visible">
  <ul class="nav navbar-nav">
    <li>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        Site Manager <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Bank Transfers", pending_transfers_path %></li>
        <li><%= link_to "Bookings", bookings_path %></li>
        <li><%= link_to "Listings", rooms_path %></li>
        <li><%= link_to "Images", uploads_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Areas", areas_path %></li>
        <li><%= link_to "Countries", locations_path %></li>
      </ul>
    </li>
  </ul>
</div>

<div class="container">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.name %></td>
        <td><%= area.location.name %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path, class: "btn btn-primary" %>
</div>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form' %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<%= render 'layouts/header_full' %>

<div class="container-full">
<div class="row">
  <div class="col-md-3 zeroRight desktop-visible">
    <div class="filterbar">
      MODIFY SEARCH<span class="glyphicon glyphicon-chevron-down glyphRight" aria-hidden="true"></span> 
    </div>
  </div>
  <div class="col-md-9 zeroLeft">
    <div class="infobar">
      Showing 1 - 1 of 1 results for Kota Kinabalu
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-3 zeroRight desktop-visible">
    <div class="sidebar">
      <div style="padding: 15px;">
      <%= search_form_for @search, url: area_path(@area), html: { method: :get } do |f| %>
        
            <%= f.select :area_id_eq, options_from_collection_for_select(Area.all, "id", "name", @search.area_id_eq), {:prompt => "Select destination"}, class: "form-control marBot-10" %>
          

        <div class="row">
          <div class="col-md-6 padRight-5">
            <%= text_field_tag :date, params[:date], placeholder: 'Select date', autocomplete: 'off', readonly: true, class: "form-control marBot-10 datepicker1" %>
          </div>
          <div class="col-md-6 padLeft-5">
            <%= select_tag :duration, options_for_select(Area::DURATION_SELECT), selected: "3 hours", class: "form-control marBot-10" %>
          </div>
        </div>  
          
          <%= button_tag "Find Rooms", data: {disable_with: "WAIT..."}, class: "btn btn-lg btn-danger full-width" %>
      <% end %>
      </div>
      <br>
      <div class="filter-bar">
        FILTER YOUR RESULT<span class="glyphicon glyphicon-chevron-right glyphRight" aria-hidden="true"></span> 
      </div>
      <div style="padding: 15px;">
      <%= search_form_for @search, url: area_path(@area), html: { method: :get } do |f| %>
        <%= f.select :area_id_eq, options_from_collection_for_select(Area.all, "id", "name", @search.area_id_eq), {:prompt => "Select destination"}, class: "form-control marBot-10 noBor" %>

        <%= f.label :district_cont %>
          <%= f.search_field :district_cont %>
        <div class="text-right">
        <%= button_tag "Update", data: {disable_with: "WAIT..."}, class: "btn btn-default" %>
         </div>
      <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-9">
    <div class="roomWrapper">
    <div class="row">
      <% @rooms.each do |room| %>
      <div class="col-md-6">
      <%= link_to room_path(room, start_date: @start_date, duration: @duration) do %>
        <div class="room-wrapper">
          <%= image_tag('bg.jpg') %>

          <div class="room-description">
            <div class="listing-price">
              <span class="ribbon ribbon-pale-green">MYR 50.00 <sub>/ 3 hours</sub></span> 
            </div>
            <h1><%= room.name %> Double Room</h1>
            <p><%= "#{room.district}, #{room.area.name}" %></p>
          </div>
        </div>
      <% end %>
      </div>
      <% end %>
    </div>
  </div>
  </div>
</div>
</div>

<script>
  $(document).ready(function(){
    $('.datepicker1').datepicker({
      format: 'yyyy-mm-dd',
      startDate: "+0d",
      endDate: "+90d",
      orientation: "left bottom",
      /* datesDisabled: ["2015-11-07","2015-11-10"], */
      /* daysOfWeekDisabled: "06", */
      /* daysOfWeekDisabled: "12345", */
      weekStart: "1",
      autoclose: true,
    });
  });
</script>