config/routes.rb
Rails.application.routes.draw do
  resources :uploads
  resources :locations
  resources :bookings
  
  get 'listings' => "rooms#listings"
  get 'inactive-listings' => "rooms#inactive_listings"
  
  get 'reservations' => 'bookings#reservations'
  get 'checked-in' => 'bookings#checked_in'
  get 'checked-out' => 'bookings#checked_out'
  get 'guest-cancelled' => 'bookings#guest_cancelled'
  get 'no-shows' => 'bookings#no_shows'

  get 'pending-transfers' => 'bookings#transfer_pending'
  get 'confirmed-transfers' => 'bookings#transfer_confirm'

  get 'upcoming' => "bookings#upcoming"
  get 'departed' => "bookings#departed"
  get 'cancelled' => "bookings#cancelled"
  
  match 'update_listing_status' => "rooms#update_listing_status", via: :post

  match 'update_status' => "bookings#update_status", via: :post
  match 'cancel_booking' => "bookings#cancel_booking", via: :post
  match 'checking_out' => "bookings#checking_out", via: :post
  match 'verify_transfer' => "bookings#verify_transfer", via: :post

  get 'rooms/update_timeslots', :as => 'update_timeslots'
  get 'rooms/block_timeslots', :as => 'block_timeslots'
  get 'rooms/block_timeslots_next', :as => 'block_timeslots_next'


  get 'payment-instruction' => "bookings#payment_instruction"
 
  resources :rooms do
    resources :room_steps, path: "steps", only: [:show, :update]
  	collection do
  		match 'search' => 'rooms#search', via: [:get, :post], as: :search
      match 'search-refined' => 'rooms#search_refined', via: [:get, :post], as: :search_refined
  		match 'book' => 'rooms#book', via: [:get, :post], as: :book
  	end
  end

  get 'rooms/:id/calendar' => "rooms#calendar", as: :calendar
  
  resources :areas
  
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]

  root 'welcome#index'

end

app/models/room.rb
class Room < ActiveRecord::Base
  has_attached_file :cover, 
                    :styles => { :medium => "300x300>",:thumb => "100x100>" }, 
                    :s3_protocol => :https,
                    :url => ":s3_alias_url",
                    :s3_host_alias => "media.hourbeds.com",
                    :path => "/:class/covers/:id_partition/:style/:filename",
                    :default_url => "no-image.jpg"

  
  validates :name, :premise_name, :district, :location, :area_id, presence: true
  #validates_presence_of :title, :description, :on => [:update] 
  validates_attachment  :cover, 
        :content_type => { :content_type => /\Aimage\/.*\Z/ },
        :size => { :less_than => 1.megabyte }

  monetize :deposit_sens
  monetize :price_per_three_hour_sens #,
    #numericality: {
    #  greater_than_or_equal_to: 40,
      # less_than_or_equal_to: 10000
    #}
  monetize :price_per_extra_hour_sens, :price_per_extra_guest_sens#, 
    #numericality: {
    #  greater_than_or_equal_to: 5,
      # less_than_or_equal_to: 50
    #}

  belongs_to :area
	belongs_to :user
  has_many :uploads, dependent: :destroy
  accepts_nested_attributes_for :uploads, :reject_if => lambda { |t| t['image'].nil? }, :allow_destroy => true

    
  scope :located_at, -> (area_id) { where area_id: area_id}
  scope :districted_at, -> (district) { where district: district}
  scope :with_restaurant, -> { where restaurant: true }
  scope :with_bar, -> { where bar: true }
  scope :with_balcony, -> { where balcony: true }
  scope :with_free_parking, -> { where free_parking: true }
  scope :with_free_airport_shuttle, -> { where free_airport_shuttle: true}
  scope :with_free_wifi, -> { where free_wifi: true }
  scope :with_meeting_rooms, -> { where meeting_rooms: true }
  scope :with_outdoor_pool, -> { where outdoor_pool: true }
  scope :with_indoor_pool, -> { where indoor_pool: true }
  scope :with_spa, -> { where spa: true }
  scope :with_beauty_center, -> { where beauty_center: true }
  scope :with_fitness_room, -> { where fitness_room: true }
  scope :with_massage, -> { where massage: true }
  scope :with_sauna, -> { where sauna: true }
  scope :with_jacuzzi, -> { where jacuzzi: true }
  scope :with_kitchen, -> { where kitchen: true }

  scope :that_are_active, -> { where active: true }

  #scope :less_than, -> (max_price) { where('price_per_three_hour <= ?', max_price )}
  #scope :more_than, -> (min_price) { where('price_per_three_hour >= ?', min_price )}
  HOUR_SELECT = [ ["12:00 AM", "0"], ["1:00 AM", "1"], ["2:00 AM", "2"], ["3:00 AM", "3"], ["4:00 AM", "4"],
                  ["5:00 AM", "5"], ["6:00 AM", "6"], ["7:00 AM", "7"], ["8:00 AM", "8"], ["9:00 AM", "9"], 
                  ["10:00 AM", "10"], ["11:00 AM", "11"], ["12:00 PM", "12"], ["1:00 PM", "13"], ["2:00 PM", "14"], 
                  ["3:00 PM", "15"], ["4:00 PM", "16"], ["5:00 PM", "17"], ["6:00 PM", "18"], ["7:00 PM", "19"], 
                  ["8:00 PM", "20"], ["9:00 PM", "21"], ["10:00 PM", "22"], ["11:00 PM", "23"] 
                ]

  def self.district(area)
    where(area_id: area).pluck(:district).uniq.sort_by!{ |d| d }
  end
    
  def self.total_rooms(area)
    where(area_id: area).size
  end

  def room_rates(hour)
    extra_hour = hour.to_i - 3
    total = (extra_hour * price_per_extra_hour) + price_per_three_hour
    (total * 1.2)
  end

  #def self.timeslots_for(date, duration)
  #  (Date.parse(date).beginning_of_day.to_i..(Date.parse(date).end_of_day - duration.to_i.hour + 1.second).to_i).to_a.in_groups_of(60.minutes).collect(&:first).collect { |t| Time.at(t).utc }
  #end

  def self.timeslots_for(date, start_hour, end_hour)
    ((Date.parse(date).beginning_of_day + start_hour.hour).to_i..(Date.parse(date).beginning_of_day + end_hour.hour).to_i).to_a.in_groups_of(60.minutes).collect(&:first).collect { |t| Time.at(t).utc }
  end

  #def self.timeslot_select(date, duration)
  #  (Date.parse(date).beginning_of_day.to_i..(Date.parse(date).end_of_day - duration.to_i.hour + 1.second).to_i).to_a.in_groups_of(60.minutes).collect(&:first).collect { |t| Time.at(t).utc.strftime("%l:%M %p") }
  #end

  def self.timeslot_select(date, start_hour, end_hour)
    ((Date.parse(date).beginning_of_day + start_hour.hour).to_i..(Date.parse(date).beginning_of_day + end_hour.hour).to_i).to_a.in_groups_of(60.minutes).collect(&:first).collect { |t| Time.at(t).utc.strftime("%l:%M %p") }
  end

  def available?(date, duration)
    timeslots = Room.timeslots_for(date) #Room.timeslots_for(date)
    bookings = Booking.where(room_id: id)
    result = []

    timeslots.each do |timeslot|
      bookings.each do |booking|
        if (timeslot + "#{duration}".to_i.hour).between?(booking.check_in, booking.check_out)
          result << "N/A"
        else
          result << "Avail"
        end
      end
    end
    result
    result.any? {|r| r == "Avail"}
  end

  def booking_blank?(date)
    bookings = Booking.where(room_id: id, start_date: date).blank?
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy, :book, :calendar, :update_timeslots, :update_listing_status, :block_timeslots, :block_timeslots_next]
  before_action :check_arrival, :authenticate_user!,  only: [:book]
  before_filter :admin_signed_in?, only: [:index]

  # GET /rooms
  # GET /rooms.json
  def book
    @booking = Booking.new
    @duration = params[:hour].to_i
    @guest = params[:guest].to_i
    @start_date = params[:date]
    @check_in = params[:check_in].to_datetime
    @check_out = @check_in + @duration.hour    
    
    @total = params[:grand_total].to_money
    
    @pay_later =  @total/1.2
    @pay_now = @total - @pay_later
    #@client_token = Braintree::ClientToken.generate #Braintree
    @grand_total = @total + @room.deposit
  end

  def search
    @area = Area.find_by_id(params[:area])

    if @area.present?
      @areas = Area.all.includes(:location)
      ## Search with timeslots ## @bookings = Booking.where(start_date: params[:start_date]).that_are_paid

      search = Room.that_are_active.where(nil).includes(:area) # creates an anonymous scope
      search = search.located_at(params[:area]) if params[:area].present?
      search = search.districted_at(params[:district]) if params[:district].present?
      
      search = search.ransack(params[:q])
      @rooms = search.result(distinct: true).order('price_per_three_hour_sens ASC')
    else
      redirect_to root_url
    end
  end

  def search_refined
    @area = Area.find_by_id(params[:area])
    
    if @area.present?

      @areas = Area.all.includes(:location)
      ## Search with timeslots ## @bookings = Booking.where(start_date: params[:start_date]).that_are_paid

      search = Room.that_are_active.where(nil).includes(:area) # creates an anonymous scope
      search = search.located_at(params[:area]) if params[:area].present?
      search = search.districted_at(params[:district]) if params[:district].present?
      search = search.with_restaurant if params[:restaurant].present?
      search = search.with_bar if params[:bar].present?
      search = search.with_balcony if params[:balcony].present?
      search = search.with_free_wifi if params[:free_wifi].present?
      search = search.with_free_parking if params[:free_parking].present?
      search = search.with_free_airport_shuttle if params[:free_airport_shuttle].present?
      search = search.with_meeting_rooms if params[:meeting_rooms].present?
      search = search.with_outdoor_pool if params[:outdoor_pool].present?
      search = search.with_indoor_pool if params[:indoor_pool].present?
      search = search.with_spa if params[:spa].present?
      search = search.with_beauty_center if params[:beauty_center].present?
      search = search.with_fitness_room if params[:fitness_room].present?
      search = search.with_massage if params[:massage].present?
      search = search.with_sauna if params[:sauna].present?
      search = search.with_jacuzzi if params[:jacuzzi].present?
      search = search.with_kitchen if params[:kitchen].present?
      search = search.ransack(params[:q])
      @rooms = search.result(distinct: true).order('price_per_three_hour_sens ASC')
    else
      redirect_to root_url
    end
  end

  #def update_timeslots_alt
  #  bookings = Booking.where(room_id: params[:id]) #Booking.where(room_id: params[:id], start_date: params[:start_date])
  #  @timeslots = Room.timeslots_for(params[:start_date], params[:duration]) #Room.timeslots_for(params[:start_date])
  #  @timeslot_select = Room.timeslot_select(params[:start_date], params[:duration]) #Room.timeslot_select(params[:start_date])

  #  @result = []

  #  @timeslots.each do |ts|
  #    bookings.each do |booking|
  #      if ts.between?(booking.check_in - params[:duration].to_i.hour, booking.check_out)
  #        @result << ts
  #      end
  #    end
  #  end
  #  @result
  #end

  def update_timeslots
    room_bookings = Booking.where(room_id: params[:id]) #Booking.where(room_id: params[:id], start_date: params[:start_date])
    next_day = (params[:start_date].to_datetime + 1.day).to_date
    bookings = room_bookings.where('start_date = ? OR start_date =?', params[:start_date], next_day)
    
    @timeslots = Room.timeslots_for(params[:start_date], @room.book_start, @room.book_end) #Room.timeslots_for(params[:start_date])
    @timeslot_select = Room.timeslot_select(params[:start_date], @room.book_start, @room.book_end) #Room.timeslot_select(params[:start_date])

    @result = []

    @timeslots.each do |ts|
      if (ts + params[:duration].to_i.hour) < params[:start_date].to_datetime.end_of_day
        bookings.each do |booking|
          if ts.between?(booking.check_in - params[:duration].to_i.hour, booking.check_out) || ts.between?(booking.check_in, booking.check_out)
            @result << ts
          end
        end
      else
        bookings.each do |booking|
          if (ts + params[:duration].to_i.hour).between?(booking.check_in - params[:duration].to_i.hour, booking.check_out) || ts.between?(booking.check_in, booking.check_out)
            @result << ts
          end
        end
      end
    end
    @result
  end

  def block_timeslots
    room_bookings = Booking.where(room_id: params[:id]) #Booking.where(room_id: params[:id], start_date: params[:start_date])
    next_day = (params[:start_date].to_datetime + 1.day).to_date
    bookings = room_bookings.where('start_date = ? OR start_date =?', params[:start_date], next_day)

    @timeslots = Room.timeslots_for(params[:start_date], @room.book_start, @room.book_end)
    @timeslot_select = Room.timeslot_select(params[:start_date], @room.book_start, @room.book_end)

    @result = []

    @timeslots.each do |ts|
      bookings.each do |booking|
        if ts.between?(booking.check_in, booking.check_out - 1.second)
          @result << ts
        end
      end
    end
    @result
  end

  def block_timeslots_next
    room_bookings = Booking.where(room_id: params[:id]) #Booking.where(room_id: params[:id], start_date: params[:start_date])
    next_day = (params[:start_date].to_datetime + 1.day).to_date
    bookings = room_bookings.where('start_date = ? OR start_date =?', params[:start_date], next_day)

    @timeslots = Room.timeslots_for(params[:start_date], @room.book_start, @room.book_end)
    @timeslot_select = Room.timeslot_select(params[:start_date], @room.book_start, @room.book_end)

    @result_next = []

    @timeslots.each do |ts|
      bookings.each do |booking|
        if ts.between?(booking.check_in, booking.check_out - 1.second)
          @result_next << ts
        end
      end
      if ts <= params[:check_in]
          @result_next << ts
      end
    end
    @result_next
  end



  ### Members Area ###

  def listings
    @rooms = Room.where(user_id: current_user.id, active: true)
  end

  def inactive_listings
    @rooms = Room.where(user_id: current_user.id, active: false)
  end

  def update_listing_status
    if params[:commit] == "Deactivate"
      @room.update_attribute(:active, false)
      redirect_to listings_url
    elsif params[:commit] == "Activate"
      @room.update_attribute(:active, true)
      redirect_to inactive_listings_url
    end
  end

  ####################
  
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    if params[:start_date].to_date < Date.today || params[:duration].to_i < 3 || params[:duration].to_i > 9
      redirect_to root_url, notice: "Oops! Something went wrong!"
    else
      @uploads = Upload.where(room_id: @room.id)
      gon.latitude = @room.latitude
      gon.longitude = @room.longitude
      gon.price_per_extra_hour = @room.price_per_extra_hour_sens

      @timeslots = Room.timeslots_for(params[:start_date], @room.book_start, @room.book_end) #Room.timeslots_for(params[:start_date])
      @timeslot_select = Room.timeslot_select(params[:start_date], @room.book_start, @room.book_end) #Room.timeslot_select(params[:start_date])
    end
    #@result = []

    #@timeslots.each do |ts|
    #  @bookings.each do |booking|
    #    if ts.to_datetime.between?(booking.check_in - params[:duration].to_i.hour, booking.check_out)
    #      @result << ts
    #    end
    #  end
    #end
    #@result
  end

  # GET /rooms/new
  def new
    @room = Room.new

    6.times do
      @room.uploads.build
    end
  end

  # GET /rooms/1/edit
  def edit
    @timeslot_select = Room.timeslot_select(Date.today.to_s, 0, 23) #Room.timeslot_select(params[:start_date])
    @timeslots = Room.timeslots_for(Date.today.to_s, 0, 23)

    @bookings = Booking.where(room_id: @room.id)
    @blocks = Booking.where(room_id: @room.id, payment_method: "Block")

    image_number = 6 - @room.uploads.size
    image_number.times do
      @room.uploads.build
    end
    @booking = Booking.new
  end

  def calendar
    @timeslot_select = Room.timeslot_select(Date.today.to_s, 0, 23) #Room.timeslot_select(params[:start_date])
    @timeslots = Room.timeslots_for(Date.today.to_s, 0, 23)

    @bookings = Booking.where(room_id: @room.id)
    @blocks = Booking.where(room_id: @room.id, payment_method: "Block")

    @booking = Booking.new
  end

  

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_room_step_path(room_id: @room.id, id: "about") }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to edit_room_url(@room), notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for(@room) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :booking_start %>
    <%= f.input :booking_end %>
    <%= f.input :active %>
    <%= f.input :location %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.input :district %>
    <%= f.association :area %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rooms/backup.html.erb



          <label>Arrival</label>
          <% if @bookings.present? %>
            <select name="arrival" id="arrival" class="form-input marBot-15 noBor select-fix">
              <option value="">Select time</option>
                <%= Room::TIME_SELECT.each do |ts| %>
                  <% @bookings.each do |booking| %>
                    <% if ts.between?(booking.check_in_time, booking.check_out_time) %>
                      <option disabled="disabled" value="<%= ts %>"><%= ts %></option>
                    <% else %>
                      <option value="<%= ts %>"><%= ts %></option>
                    <% end %>
                  <% end %>
                <% end %>
            </select>
          <% else %>
            <%= select_tag :arrival, options_for_select(Room::TIME_SELECT), prompt: "Select time", class: "form-input marBot-15 noBor select-fix" %>
          <% end %>

          <label>Arrival</label>
          <% if @bookings.present? %>

            <% @result = [] %>
            
                <%= Room::TIME_SELECT.each do |ts| %>
                  <% @bookings.each do |booking| %>
                    <% if ts.between?(booking.check_in_time, booking.check_out_time) %>
                      @result << ts
                    <% end %>
                  <% end %>
                <% end %>
            
            <% @result %>
          <% else %>
            <%= select_tag :arrival, options_for_select(Room::TIME_SELECT), prompt: "Select time", class: "form-input marBot-15 noBor select-fix" %>
          <% end %>

app/views/rooms/block_timeslots.js.erb
$('#select_from').html("<%= escape_javascript(select_tag :check_in, options_for_select(Hash[@timeslot_select.zip(@timeslots)], disabled: @result), prompt: "Select time") %>");

app/views/rooms/inactive_listings.html.erb
<% title 'Your Listings - Inactive Listings' %>
<% noindex %>
<%= render 'layouts/header' %>

<div class="subnav desktop-visible">
  <ul class="subnav-list">
    <div class="container">
      <li><%= link_to "Your Guests", reservations_path, class: "subnav-item zeroLeft" %></li>
      <li><%= link_to "Your Listings", listings_path, class: "subnav-item active" %></li>
      <li><%= link_to "Your Staycations", upcoming_path, class: "subnav-item" %></li>
      <li><%= link_to "Your Account", edit_user_path(current_user), class: "subnav-item" %></li>
    </div>
  </ul>
</div>
<div id="mobile-subnav" class="mobile-visible">
  <ul class="nav navbar-nav">
    <li>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        Your Listings <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Active Listings", listings_path %></li>
        <li><%= link_to "Inactive Listings", inactive_listings_path %></li>
        <li><%= link_to "Add New Listing", new_room_path %></li>
      </ul>
    </li>
  </ul>
</div>
<div class="container">
<div class="row">
  <div class="col-md-3 desktop-visible">
    <ul class="sidebar-list">
      <li><%= link_to "Active Listings", listings_path %></li>
      <li><%= link_to "Inactive Listings", inactive_listings_path, class: "active" %></li>
    </ul>
    <br>
    <%= link_to "Add New Listing", new_room_path, class: "btn btn-lg btn-primary full-width" %>
  </div>
  <div class="col-md-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Inactive Listings</h3>
    </div>
    <div class="panel-body">
      <% @rooms.each do |room| %>
        <div class="listing-wrapper">
          <div class="row">
            <div class="col-md-3 desktop-visible">
              <%= image_tag room.cover.url %>
            </div>
            <div class="col-md-7">
              <h4><%= room.name %></h4>
              <p><%= link_to "Edit Calendar", calendar_path(room) %> | <%= link_to "Edit Listing", edit_room_path(room) %></p>
              <% if room.title.blank? || room.description.blank? || room.cover.blank? %>
                <%= image_tag 'lock.png', class: "icon-sm" %> <small>To activate, room must have a title, description and cover photo.</small>
              <% end %> 
            </div>
            <div class="col-md-2">
              <%= form_tag update_listing_status_path(id: room) do %>
                <% if room.title.blank? || room.description.blank? || room.cover.blank? %>
                  <%= submit_tag "Activate", disabled: true, class: "btn btn-success full-width" %>
                <% else %>
                  <%= submit_tag "Activate", class: "btn btn-success full-width" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <hr>
      <% end %>
    </div>
  </div>
    
  </div>
</div>
</div>

app/views/rooms/index.html.erb
<% title 'Admin - Listings' %>
<% noindex %>
<%= render 'layouts/header' %>

<div class="subnav desktop-visible">
  <ul class="subnav-list">
    <div class="container">
      <li><%= link_to "Bank Transfers", pending_transfers_path, class: "subnav-item zeroLeft" %></li>
      <li><%= link_to "Bookings", bookings_path, class: "subnav-item" %></li>
      <li><%= link_to "Listings", rooms_path, class: "subnav-item active" %></li>
      <li><%= link_to "Images", uploads_path, class: "subnav-item" %></li>
      <li><%= link_to "Users", users_path, class: "subnav-item" %></li>
      <li><%= link_to "Areas", areas_path, class: "subnav-item" %></li>
      <li><%= link_to "Locations", locations_path, class: "subnav-item" %></li>
    </div>
  </ul>
</div>
<div id="mobile-subnav" class="mobile-visible">
  <ul class="nav navbar-nav">
    <li>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        Site Manager <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Bank Transfers", pending_transfers_path %></li>
        <li><%= link_to "Bookings", bookings_path %></li>
        <li><%= link_to "Listings", rooms_path %></li>
        <li><%= link_to "Images", uploads_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Areas", areas_path %></li>
        <li><%= link_to "Countries", locations_path %></li>
      </ul>
    </li>
  </ul>
</div>
<div class="container">
<div class="table-responsive">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Room</th>
      <th>Description</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.id %></td>
        <td><%= room.name %></td>
        <td><%= link_to room.title, room_path(room, start_date: Date.today, duration: 3) %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

app/views/rooms/listings.html.erb
<% title 'Your Listings - Active Listings' %>
<% noindex %>
<%= render 'layouts/header' %>

<div class="subnav desktop-visible">
  <ul class="subnav-list">
    <div class="container">
      <li><%= link_to "Your Guests", reservations_path, class: "subnav-item zeroLeft" %></li>
      <li><%= link_to "Your Listings", listings_path, class: "subnav-item active" %></li>
      <li><%= link_to "Your Staycations", upcoming_path, class: "subnav-item" %></li>
      <li><%= link_to "Your Account", edit_user_path(current_user), class: "subnav-item" %></li>
    </div>
  </ul>
</div>
<div id="mobile-subnav" class="mobile-visible">
  <ul class="nav navbar-nav">
    <li>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        Your Listings <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Active Listings", listings_path %></li>
        <li><%= link_to "Inactive Listings", inactive_listings_path %></li>
        <li><%= link_to "Add New Listing", new_room_path %></li>
      </ul>
    </li>
  </ul>
</div>
<div class="container">
<div class="row">
  <div class="col-md-3 desktop-visible">
    <ul class="sidebar-list">
      <li><%= link_to "Active Listings", listings_path, class: "active" %></li>
      <li><%= link_to "Inactive Listings", inactive_listings_path %></li>
    </ul>
    <br>
    <%= link_to "Add New Listing", new_room_path, class: "btn btn-lg btn-primary full-width" %>
  </div>
  <div class="col-md-9">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Active Listings</h3>
    </div>
    <div class="panel-body">
      <% @rooms.each do |room| %>
        <div class="listing-wrapper">
          <div class="row">
            <div class="col-md-3 desktop-visible">
              <%= image_tag room.cover.url %>
            </div>
            <div class="col-md-7">
              <h4><%= room.name %></h4>
              <p><small><%= room.title %></small></p>
              <p><%= link_to "Edit Calendar", calendar_path(room) %> | <%= link_to "Edit Listing", edit_room_path(room) %></p>
            </div>
            <div class="col-md-2">
              <%= form_tag update_listing_status_path(id: room) do %>
                <%= submit_tag "Deactivate", class: "btn btn-default full-width" %>
              <% end %>
            </div>
          </div>
        </div>
        <hr>
    <% end %>
    </div>
  </div>
    
  </div>
</div>
</div>