config/routes.rb
Rails.application.routes.draw do
  resources :uploads
  resources :locations
  resources :bookings
  
  get 'listings' => "rooms#listings"
  get 'inactive-listings' => "rooms#inactive_listings"
  
  get 'reservations' => 'bookings#reservations'
  get 'checked-in' => 'bookings#checked_in'
  get 'checked-out' => 'bookings#checked_out'
  get 'guest-cancelled' => 'bookings#guest_cancelled'
  get 'no-shows' => 'bookings#no_shows'

  get 'pending-transfers' => 'bookings#transfer_pending'
  get 'confirmed-transfers' => 'bookings#transfer_confirm'

  get 'upcoming' => "bookings#upcoming"
  get 'departed' => "bookings#departed"
  get 'cancelled' => "bookings#cancelled"
  
  match 'update_listing_status' => "rooms#update_listing_status", via: :post

  match 'update_status' => "bookings#update_status", via: :post
  match 'cancel_booking' => "bookings#cancel_booking", via: :post
  match 'checking_out' => "bookings#checking_out", via: :post
  match 'verify_transfer' => "bookings#verify_transfer", via: :post

  get 'rooms/update_timeslots', :as => 'update_timeslots'
  get 'rooms/block_timeslots', :as => 'block_timeslots'
  get 'rooms/block_timeslots_next', :as => 'block_timeslots_next'


  get 'payment-instruction' => "bookings#payment_instruction"
 
  resources :rooms do
    resources :room_steps, path: "steps", only: [:show, :update]
  	collection do
  		match 'search' => 'rooms#search', via: [:get, :post], as: :search
      match 'search-refined' => 'rooms#search_refined', via: [:get, :post], as: :search_refined
  		match 'book' => 'rooms#book', via: [:get, :post], as: :book
  	end
  end

  get 'rooms/:id/calendar' => "rooms#calendar", as: :calendar
  
  resources :areas
  
  devise_for :users
  resources :users, only: [:index, :show, :edit, :update]

  root 'welcome#index'

end

app/models/upload.rb
class Upload < ActiveRecord::Base
    has_attached_file :image, 
                      :styles => { :medium => "300x300>",:thumb => "100x100>" }, 
                      :s3_protocol => :https, 
                      :url => ":s3_alias_url",
                      :s3_host_alias => "media.hourbeds.com",
                      :path => "/:class/images/:id_partition/:style/:filename",
                      :default_url => "no-image.jpg"
	
	validates_attachment :image, 
				:content_type => { :content_type => /\Aimage\/.*\Z/ },
				:size => { :less_than => 1.megabyte }
				
	belongs_to :room
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_filter :admin_signed_in?, only: [:index]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all.includes(:room)
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(upload_params)
    
    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
        format.json { render :show, status: :created, location: @upload }
      else
        format.html { render :new }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { render :show, status: :ok, location: @upload }
      else
        format.html { render :edit }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload = Upload.find(params[:id])
    if @upload.destroy    
      render json: { message: "File deleted from server" }
    else
      render json: { message: @upload.errors.full_messages.join(',') }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_upload
     # @upload = Upload.find(params[:id])
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:room_id, :image)
    end
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_form.html.erb
<%= simple_form_for(@upload, html: { multipart: true, id: "new_upload", class: "dropzone"}) do |f| %>
  <%= f.error_notification %>

  <div class="fallback">
    <%= f.input :image %>
    <%= f.button :submit %>
  </div>
<% end %>

<script>
$(document).ready(function(){
	// disable auto discover
	Dropzone.autoDiscover = false;

	// grap our upload form by its id
	$("#new_upload").dropzone({
		// restrict image size to a maximum 1MB
		maxFilesize: 1,
		// changed the passed param to one accepted by
		// our rails app
		paramName: "upload[image]",
		// show remove links on each image upload
		addRemoveLinks: true,
		// if the upload was successful
		success: function(file, response){
			// find the remove button link of the uploaded file and give it an id
			// based of the fileID response from the server
			$(file.previewTemplate).find('.dz-remove').attr('id', response.fileID);
			// add the dz-success class (the green tick sign)
			$(file.previewElement).addClass("dz-success");
		},
		//when the remove button is clicked
		removedfile: function(file){
			// grap the id of the uploaded file we set earlier
			var id = $(file.previewTemplate).find('.dz-remove').attr('id'); 

			// make a DELETE ajax request to delete the file
			$.ajax({
				type: 'DELETE',
				url: '/uploads/' + id,
				success: function(data){
					console.log(data.message);
				}
			});
		}
	});	
});
</script>

app/views/uploads/edit.html.erb
<h1>Editing Upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<% title 'Admin - Images' %>
<% noindex %>
<%= render 'layouts/header' %>

<div class="subnav desktop-visible">
  <ul class="subnav-list">
    <div class="container">
      <li><%= link_to "Bank Transfers", pending_transfers_path, class: "subnav-item zeroLeft" %></li>
      <li><%= link_to "Bookings", bookings_path, class: "subnav-item" %></li>
      <li><%= link_to "Listings", rooms_path, class: "subnav-item" %></li>
      <li><%= link_to "Images", uploads_path, class: "subnav-item active" %></li>
      <li><%= link_to "Users", users_path, class: "subnav-item" %></li>
      <li><%= link_to "Areas", areas_path, class: "subnav-item" %></li>
      <li><%= link_to "Countries", locations_path, class: "subnav-item" %></li>
    </div>
  </ul>
</div>
<div id="mobile-subnav" class="mobile-visible">
  <ul class="nav navbar-nav">
    <li>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        Site Manager <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
        <li><%= link_to "Bank Transfers", pending_transfers_path %></li>
        <li><%= link_to "Bookings", bookings_path %></li>
        <li><%= link_to "Listings", rooms_path %></li>
        <li><%= link_to "Images", uploads_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li><%= link_to "Areas", areas_path %></li>
        <li><%= link_to "Countries", locations_path %></li>
      </ul>
    </li>
  </ul>
</div>

<div class="container">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Room</th>
      <th>Image</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= upload.id %></td>
        <td>
          <%= link_to upload.room.title, room_path(id: upload.room_id, start_date: Date.today, duration: 3) %>
          <p><small><%= upload.room.name %></small></p>
        </td>
        <td><%= image_tag upload.image.url(:thumb) %></td>
        <td><%= link_to 'Edit', edit_upload_path(upload) %></td>
        <td><%= link_to 'Destroy', upload, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/uploads/new.html.erb
<div class="container">

<h1>New Upload</h1>

<%= simple_form_for(@upload, html: { multipart: true, id: "new_upload", class: "dropzone"}) do |f| %>
  <%= f.error_notification %>

  <div class="fallback">
    <%= f.input :image %>
    <%= f.button :submit %>
  </div>


<% end %>

</div>
<script>
$(document).ready(function(){
	// disable auto discover
	Dropzone.autoDiscover = false;

	// grap our upload form by its id
	$("#new_upload").dropzone({
		// restrict image size to a maximum 1MB
		maxFilesize: 1,
		// changed the passed param to one accepted by
		// our rails app
		paramName: "upload[image]",
		// show remove links on each image upload
		addRemoveLinks: true,
		// if the upload was successful
		success: function(file, response){
			// find the remove button link of the uploaded file and give it an id
			// based of the fileID response from the server
			$(file.previewTemplate).find('.dz-remove').attr('id', response.fileID);
			// add the dz-success class (the green tick sign)
			$(file.previewElement).addClass("dz-success");
		},
		//when the remove button is clicked
		removedfile: function(file){
			// grap the id of the uploaded file we set earlier
			var id = $(file.previewTemplate).find('.dz-remove').attr('id'); 

			// make a DELETE ajax request to delete the file
			$.ajax({
				type: 'DELETE',
				url: '/uploads/' + id,
				success: function(data){
					console.log(data.message);
				}
			});
		}
	});	
});
</script>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @upload.room_id %>
</p>

<%= link_to 'Edit', edit_upload_path(@upload) %> |
<%= link_to 'Back', uploads_path %>